server:
  port: 8080


thymeleaf:
  prefix: classpath:/templates/

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ShrioDb?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

# 开发环境
logging:
  level:
    shiro.dao: debug

#redis配置
redis:
  host: localhost
  port: 6379
  timeout: 2000s
